<?php

namespace SB\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function myFindOne($id)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->where('a.id = :id')
            ->setParameter('id', $id);
        return $qb->getQuery()->getResult();
    }

    public function findByAuthorAndDate($author, $date)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.author = :author')
            ->setParameter('author', $author)
            ->andWhere('a.date < :date')
            ->setParameter('date', $date)
            ->orderBy('a.date', 'DESC');

        return $qb->getQuery()->getResult();
    }

    public function getAdvertPublished()
    {
        $qb = $this->getEntityManager()->createQuery(
            ' SELECT adv
            FROM SBPlatformBundle:Advert adv
            WHERE published = TRUE
        ');
        return $qb->getResult();
    }

    public function getAdvert($nbPerPage, $page)
    {
        $qb = $this->getEntityManager()->createQuery(
            'SELECT adv
            FROM SBPlatformBundle:Advert adv
            WHERE adv.published = TRUE
            ORDER BY adv.date DESC
            ');
        $qb->setFirstResult(($page-1)*$nbPerPage)->setMaxResults($nbPerPage);
        return new Paginator($qb, true);
    }

    public function getAdvertInfos($id)
    {
        $qb = $this->getEntityManager()->createQuery(
            'SELECT adv, img, cat
            FROM SBPlatformBundle:Advert adv
            JOIN adv.image img
            JOIN adv.categories cat
            ORDER BY adv.date DESC');
        return $qb->getResult();
    }

    public function getAdvertWithCategories(array $categoryNames)
    {

        $qb = $this->getEntityManager()->createQuery(
            'SELECT adv, c
            FROM SBPlatformBundle:Advert adv
            JOIN adv.categories c
            WHERE c.name IN (?1)');
        $qb->setParameter(1, $categoryNames);
        return $qb->getResult();
    }
}
