<?php

namespace SB\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
    public function getApplicationWithAdvert($limit)
    {
        $qb = $this->getEntityManager()->createQuery(
            'SELECT adv
            FROM SBPlatformBundle:Application a
            JOIN a.advert adv'
        );
        $qb->setMaxResults($limit);
        return $qb->getResult();
    }
}
